language: cpp
compiler:
    - gcc
    - clang

branches:
    only:
        - master

before_install:
    - sudo apt-get --yes update
    - sudo apt-get --yes install g++-4.8
    - if [ "$CXX" == "g++" ]; then export CXX=g++-4.8; fi
    - sudo apt-get --yes install ninja-build
    - sudo apt-get --yes install liblua5.2-dev
    - sudo apt-get install libsfml-dev

script: ./bootstrap.py --ci --cxx=$CXX && ninja
